### PR TITLE
increase `keysOpIndex` in `assignNextSigningKeys`

### PR DESCRIPTION
**Pull request by arwer13**
to make less difficult to track used keys

### CODE REVIEW

**Review by loga4 — APPROVED** [review]
lgtm

**Review by krogla — APPROVED** [review]

**Comment by TheDZhon** [comment]
LGTM.

P.S. Interesting `assertNoEvent` helper.
Usually, I just go with `assertAmountOfEvents` passing 0 occurrences.

**Review by TheDZhon — APPROVED** [review]
LGTM.

P.S. Interesting assertNoEvent helper.
Usually, I just go with assertAmountOfEvents passing 0 occurrences.

**Review by avsetsin — APPROVED** [review]
lgtm

**Comment by TheDZhon** [comment]
The code is adopter for another PR: #401

**Pull request closed without merging**
